/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rcjava.unsign;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests the plugin
 * @author Ryan Cuprak
 */
class UnsignPluginPluginTest {

    /**
     * Verifies that the plugin is registered
     */
    @Test
    void pluginRegistersATask() {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("com.rcjava.unsign");
        assertNotNull(project.getTasks().findByName("unsign"));
        project.getTasks().findByName("unsign");
    }
}
